---
title: "Build the big data table"
author: "Clay Morrow"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages}
library(tidyverse)
```

```{r script_parameters}
# path to NEON data directory
neon_data_dir = "neon-data/data/eight_sites"
```


## Load and clean the mammal data

```{r mammal-data}
# load the small mammal trapping data products
mammal_prods <- readRDS(file.path(neon_data_dir, "mammal-trap-data.rds"))

# Extract a tibble of the "mammals per trap night" data object
full_data <- mammal_prods$mam_pertrapnight |> tibble()

# Keep only necessary columns
full_data <- full_data %>% select(
  # ID variables (location)
  uid, nightuid, domainID, siteID, plotID, trapCoordinate, 
  # Location information
  plotLat = decimalLatitude, plotLon = decimalLongitude, plotElev = elevation,
  landClass = nlcdClass, 
  # time variables
  collectDate,
  # mammal ID variables
  tagID, taxonID, scientificName, nativeStatusCode,
  # captured mammal data
  sex, recapture, fate, lifeStage, testes, nipples, pregnancyStatus, vagina,
  hindfootLength, earLength, tailLength, totalLength,
  weight, 
  # mammal parasite information
  larvalTicksAttached, nymphalTicksAttached, adultTicksAttached, tickNumber, 
  additionalParasites, 
  # biological sampling IDs
  bloodSampleID, bloodSampleBarcode, fecalSampleID, fecalSampleBarcode,
  earSampleID, earSampleBarcode, hairSampleID, hairSampleBarcode, 
  voucherSampleID, voucherSampleBarcode,
  # NEON data status variables
  publicationDate, release
) %>% distinct()

# TODO: Clean mammal data and keep only important columns
# add new time variables
full_data <- full_data |> 
  mutate(
    year = year(collectDate),
    month = month(collectDate),
    day = day(collectDate),
    DOY = yday(collectDate),
    date = date(collectDate)
  ) |> 
  # group these columns with the other time ones
  relocate(year:date, .before = collectDate)

# number of observations in the mammal table 
n_mammals <- nrow(full_data)
```

```{r}
# extract the plot night meta data
plot_nights <- mammal_prods$mam_perplotnight %>% 
  tibble()

# select only the important columns from meta data, and add lengths
plot_nights <- plot_nights %>%
  select(
    nightuid, collectDate, eventID, trapSampleMethod = mammalGridSamplingMethod,
    samplingIssues = samplingImpractical
  )

# join the plot nights with the full data
full_data <- full_data %>% 
  full_join(plot_nights) %>% 
  relocate(eventID:samplingIssues, .after = trapCoordinate)

# check the sizes
stopifnot(nrow(full_data) == n_mammals)
```

```{r location_meta_data}
# Load locations and meta data of NEON sites
site_locations <- read.csv(
  "infection-modeling/data/raw-data/NEON-SiteMap-Table.csv"
) |> 
  tibble()

# get the vector of colors to use for sites
site_cols <- site_locations$color_hex

# keep only columns of interest
site_locations <- site_locations %>% 
  select(
    siteID = siteCode, siteName, siteType = type, stateCode, 
    siteLat = latitude, siteLon = longitude
) %>% distinct()

# merge with full data
full_data <- full_join(full_data, site_locations) %>% 
  relocate(siteName:siteLon, .after = trapCoordinate)
stopifnot(nrow(full_data) == n_mammals)

# Load locations and meta data of NEON small mammal traps
trap_locations <- readRDS(
  file.path(
    neon_data_dir,
    "location_data/small-mammal-trap-locations.rds"
  )
) %>% tibble()

# keep only columns of interest
trap_locations <- trap_locations %>% 
  select(
    siteID, plotID, trapCoordinate, 
    trapLat = adjDecimalLatitude, trapLon = adjDecimalLongitude,
    trapElev = adjElevation
  ) %>% distinct()

# merge with full data
full_data <- full_join(full_data, trap_locations) %>% 
  relocate(trapLat:trapElev, .after = trapCoordinate)
stopifnot(nrow(full_data) == n_mammals)
```

```{r removeObs_A, include = FALSE}
# remove the plot_nights object
rm(plot_nights)
rm(mammal_prods)
gc()
```

```{r refactor_ticks}
# refactor tick loads
full_data <- full_data %>% 
  mutate(
    # update the tick counts
    tickNumber = if_else(
      larvalTicksAttached != "Y" & 
        nymphalTicksAttached != "Y" & 
        adultTicksAttached != "Y" & 
        tickNumber != "No count performed", true = "0", false = tickNumber
    ) %>% factor(levels = c("0", "1-5", "6-20", ">20"), ordered = TRUE),
    # convert the tick attached variables to logical
    nymphalTicksAttached = case_when(
      nymphalTicksAttached == "Y" ~ TRUE,
      nymphalTicksAttached == "N" ~ FALSE,
      .default = NA
    ),
    larvalTicksAttached = case_when(
      larvalTicksAttached == "Y" ~ TRUE,
      larvalTicksAttached == "N" ~ FALSE,
      .default = NA
    ),
    adultTicksAttached = case_when(
      adultTicksAttached == "Y" ~ TRUE,
      adultTicksAttached == "N" ~ FALSE,
      .default = NA
    )
  )
```

```{r bout_info}
# TODO: calculate bout information (start, end, and trapping days)
```


## Save the updated file

```{r}
saveRDS(full_data, "infection-modeling/data/full-data.rds")
```

